version: '3'

services:
  mariadb:
    container_name: mariadb_inception
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    restart: on-failure:10

  wordpress:
    container_name: wordpress_inception
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure:10

  nginx:
    container_name: nginx_inception
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure:10

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

networks:
 inception:
    driver: bridge
